apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache-node-1
  name: apache-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-node-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-node-1
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
